// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6YiV_7Z0WyuYjaRFH6bAX89Ums7ZmVck',
    appId: '1:35464718626:web:629e698c0b8cf72ff65d7b',
    messagingSenderId: '35464718626',
    projectId: 'mess-maven-demo',
    authDomain: 'mess-maven-demo.firebaseapp.com',
    storageBucket: 'mess-maven-demo.appspot.com',
    measurementId: 'G-SWFW5ND2NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxYZUmMCEcoLa5npGXXk-Wjao7dlWFBMg',
    appId: '1:35464718626:android:a04765f933ccc3abf65d7b',
    messagingSenderId: '35464718626',
    projectId: 'mess-maven-demo',
    storageBucket: 'mess-maven-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGivf6hn9BAhg-8kfUMK1F3KBrv7Ss8AY',
    appId: '1:35464718626:ios:48d12e8c6b7c1579f65d7b',
    messagingSenderId: '35464718626',
    projectId: 'mess-maven-demo',
    storageBucket: 'mess-maven-demo.appspot.com',
    androidClientId: '35464718626-3s7vqm7dj47g145e4quklh96ccioolst.apps.googleusercontent.com',
    iosClientId: '35464718626-77i13l7vn2a40f3g1jpsl093le8pku0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.messmavenMinorProject',
  );
}
